### ISSUE TITLE
New App name

### ISSUE THREAD

**Issue by conrad-heimbold** [dkanada/frost-icons#14]
See issue #13 , comment 2

Words that could be used inside the app name (brainstorming): 
- **white, ice, snow**
- **uniform / consistent**, meaning: **uniform look** - all icons have got only one color, and most icons are based on one of the 4 icon shape templates (circle, square, rect-vert or rect-hori)
- **flat, simple, sharp, personal**

The word "icon" should most likely occur in the name! 

Possibilities: 
- **Whicons** unfortunately **already exists**, it is the name of a **proprietary** white icon pack for Android on Google Play. 
- **Snoci** - read it **backwards** and you get **"icons"**; read it **forwards** and you get the allusion to **(white) snow**, just like **ICEcon** includes **ice** and **icon**
- **Unicon** - **uniform** look for all app **icons**. Also sounds a bit like **unicorn**: If at one point in the future, we offer the icons **both in white and original color** (switchable inside the app itself), the name "unicorn" would also fit - unicorns in the internet are often displayed in **rainbow colors** and unicorns are a common meme in the Internet. 
- **Iconsistent** (same reason as above) 

Let's see if I get more ideas in the future...

**Comment by conrad-heimbold** [comment]
**Unicon** won't work probably, because Unicon 
--quote--
is the World Unicycling Convention and Championships sanctioned by the International Unicycling Federation (IUF).
--/quote--
according to Wikipedia .

**Comment by dkanada** [comment]
I am gonna leave this open for a bit just for consideration, don't wanna have to change the app name more than once.

**Comment by dkanada** [comment]
Snoci is the most unique but it kind of sounds weird =p and technically you would never notice that it spells icons backwards so we can also just open up the options to other names that don't include the word icons as long as we include that in the description for searches.

**Comment by i-kocevski** [comment]
+1 for Unicons

**Comment by conrad-heimbold** [comment]
@dkanada : Well, if we call it **Snocicons**, you would **definitely** notice the **symmetry**.

**Comment by ikocevski** [comment]
twICEcons? Like a second version of ICEcons?

**Comment by dkanada** [comment]
I forgot about this haha, I was originally wanting to avoid generic words like icons so if I ever made any more icon packs they would be distinct from each other and not ICEcons, Whicons, Material Icons, twICEcons, et cetera. Something like using a type of cloud for the name like Stratus or Cirrus, that's all I had at the time.

**Comment by ikocevski** [comment]
What about white in a different language?
Latin albus, a plain white, (the source of the word albino)

**Comment by conrad-heimbold** [comment]
@dkanada : clouds are rather confusing, IMHO, because, well, you know: **data clouds** 
(**Google Drive; Owncloud; OneDrive;** etc.). 
@ikocevski different languages sounds good :)  Maybe french? ;) ( FR - EN )
- glace - ice
- blanc - white
- neige - snow
- uniforme, cohérent - uniform, consistent
- plan - flat
- simple - simple
- net - sharp [picture]

**Comment by conrad-heimbold** [comment]
ENGLISH - LATIN: 
- ice / crystal - crystallus / crustallus / crustallum
- white - albus
- snow - nix
- uniform, consistent - aequalis, concolor, uniformis
- flat - tabula
- simple - purus, anticu(u)s
- sharp - sagax, acutus, acer

I really like the word crystal / crustallus / ... . Maybe we can make the app name out of it...

**Comment by ikocevski** [comment]
You really did a research on this :D But it's still the boss' call.

**Comment by conrad-heimbold** [comment]
@dkanada @ikocevski Do you have any ideas how to form an app name with **crystal / crustallus / ...**?

**Comment by ikocevski** [comment]
**CrystallICE**/**Crystallice**... Like crystallize but with ICE at the end ya' know? :D

**Comment by conrad-heimbold** [comment]
@ikocevski I really like **CrystallICE** :D

**Comment by xphnx** [comment]
What about:
- Escarcha (spanish)
- Xeada (galician)
- Geleé (french)
- Brina (italian)
- Shimo (japanese)
An image...
https://muskoka411.com/start/wp-content/uploads/2016/05/frost-on-plants.jpg

**Comment by ikocevski** [comment]
Is it finally settled to be **Frost Icons**?

**Comment by dkanada** [comment]
I was just gonna go with Frost, but yeah. Now to figure out the best way to share the codebase between multiple projects.
